# Generated by Django 6.1 on 2026-09-07 09:00

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0250_cooling_infrastructure'),
        ('extras', '0144_customfield_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmpInputSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('level_trim_db', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(-18), django.core.validators.MaxValueValidator(18)])),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sonance_amp_input_settings', to='dcim.interface')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'amp input settings',
                'verbose_name_plural': 'amp input settings',
                'ordering': ('interface',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AmpOutputSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('stereo_mono', models.CharField(default='stereo', max_length=10)),
                ('dsp_preset', models.CharField(blank=True, max_length=100)),
                ('output_group', models.CharField(blank=True, max_length=1)),
                ('bridge_mode', models.BooleanField(default=False)),
                ('output_source_1', models.CharField(blank=True, max_length=2)),
                ('output_source_2', models.CharField(blank=True, max_length=2)),
                ('mode_source_2', models.CharField(blank=True, default='off', max_length=10)),
                ('output_volume', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(-70), django.core.validators.MaxValueValidator(12)])),
                ('turn_on_volume', models.DecimalField(decimal_places=1, default=-70, max_digits=4, validators=[django.core.validators.MinValueValidator(-70), django.core.validators.MaxValueValidator(12)])),
                ('maximum_volume', models.DecimalField(decimal_places=1, default=12, max_digits=4, validators=[django.core.validators.MinValueValidator(-70), django.core.validators.MaxValueValidator(12)])),
                ('gain_offset', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(-6), django.core.validators.MaxValueValidator(6)])),
                ('mute', models.BooleanField(default=False)),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sonance_amp_output_settings', to='dcim.interface')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'amp output settings',
                'verbose_name_plural': 'amp output settings',
                'ordering': ('interface',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
