# Generated by Django 6.1 on 2026-09-07 10:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0250_cooling_infrastructure'),
        ('netbox_plugin_sonance_amp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampinputsettings',
            name='level_trim_db',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(-6), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='ampoutputsettings',
            name='output_source_1',
            field=models.ForeignKey(blank=True, limit_choices_to={'sonance_amp_input_settings__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.interface'),
        ),
        migrations.AlterField(
            model_name='ampoutputsettings',
            name='output_source_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'sonance_amp_input_settings__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.interface'),
        ),
    ]
